Telegram:
  token: YOUR_TELEGRAM_BOT_TOKEN

Database:
  host: localhost
  port: 5432
  username: admin
  password: password123
  database_name: bot_database

Admins:
  telegram_user_id: 444
  username: Vladimir
